In [2]:
import numpy as np
def featureNormalize(X):
    
    mu = np.mean(X, axis=0)
    sigma = np.std(X, axis=0)

    return (X-mu)/sigma, mu, sigma

In [3]:
def computeCostMulti(X, y, theta):
    
    # Initialize some useful values
    m = len(y) # number of training examples

    error = np.dot(X,theta) - y
    J = np.dot(error.T, error) /m/2

    return J

In [4]:
def gradientDescentMulti(X, y, theta, alpha, num_iters):
    
    # Initialize some useful values
    m = len(y) # number of training examples
    J_history = np.zeros((num_iters, 1))

    for iter in range(num_iters):

        error = np.dot(X,theta) - y
        theta = theta - alpha * np.dot(X.T,error) / m

        J_history[iter][0] = computeCostMulti(X, y, theta)

    return theta, J_history

In [15]:
print('Loading data ...\n')

## Load Data
data = np.loadtxt('G:\Coursera-Machine-Learning\ml-ex1\ex1data2.txt',delimiter=",")
X = data[:, 0:2]
y = data[:, 2].reshape(-1,1)
m = len(y)

# Print out some data points
print('First 10 examples from the dataset: \n')
# no find function for python
# fprintf(' x = [%.0f %.0f], y = %.0f \n', [X(1:10,:) y(1:10,:)]');
print(X[0:10,:])
print(y[0:10])

input('Program paused. Press enter to continue.\n')

# Scale features and set them to zero mean
print('Normalizing Features ...\n')

X, mu, sigma = featureNormalize(X)
print(X)
# Add intercept term to X
X = np.vstack((np.ones(m), X.T)).T

Loading data ...

First 10 examples from the dataset: 

[[2.104e+03 3.000e+00]
 [1.600e+03 3.000e+00]
 [2.400e+03 3.000e+00]
 [1.416e+03 2.000e+00]
 [3.000e+03 4.000e+00]
 [1.985e+03 4.000e+00]
 [1.534e+03 3.000e+00]
 [1.427e+03 3.000e+00]
 [1.380e+03 3.000e+00]
 [1.494e+03 3.000e+00]]
[[399900.]
 [329900.]
 [369000.]
 [232000.]
 [539900.]
 [299900.]
 [314900.]
 [198999.]
 [212000.]
 [242500.]]


Program paused. Press enter to continue.
 


Normalizing Features ...

[[ 1.31415422e-01 -2.26093368e-01]
 [-5.09640698e-01 -2.26093368e-01]
 [ 5.07908699e-01 -2.26093368e-01]
 [-7.43677059e-01 -1.55439190e+00]
 [ 1.27107075e+00  1.10220517e+00]
 [-1.99450507e-02  1.10220517e+00]
 [-5.93588523e-01 -2.26093368e-01]
 [-7.29685755e-01 -2.26093368e-01]
 [-7.89466782e-01 -2.26093368e-01]
 [-6.44465993e-01 -2.26093368e-01]
 [-7.71822042e-02  1.10220517e+00]
 [-8.65999486e-04 -2.26093368e-01]
 [-1.40779041e-01 -2.26093368e-01]
 [ 3.15099326e+00  2.43050370e+00]
 [-9.31923697e-01 -2.26093368e-01]
 [ 3.80715024e-01  1.10220517e+00]
 [-8.65782986e-01 -1.55439190e+00]
 [-9.72625673e-01 -2.26093368e-01]
 [ 7.73743478e-01  1.10220517e+00]
 [ 1.31050078e+00  1.10220517e+00]
 [-2.97227261e-01 -2.26093368e-01]
 [-1.43322915e-01 -1.55439190e+00]
 [-5.04552951e-01 -2.26093368e-01]
 [-4.91995958e-02  1.10220517e+00]
 [ 2.40309445e+00 -2.26093368e-01]
 [-1.14560907e+00 -2.26093368e-01]
 [-6.90255715e-01 -2.26093368e-01]
 [ 6.68172729e-01 -2.26093368

In [22]:
def ones(m):
    b =[]
    for i in range(m):
        b.append(1.0)
    return b
b = ones(3)

In [28]:
print(len(b))

3


In [29]:
def transpose(m):
    rows = len(m)
    cols = len(m[0])
    MT = zero_matrix(cols, rows)
    for i in range(rows):
        for j in range(cols):
            MT[j][i] = m[i][j]
    
    return MT

In [33]:
def createMatrix(rowCount, colCount, dataList):
    mat = []
    for i in range(rowCount):
        rowList = []
        for j in range(colCount):
            # you need to increment through dataList here, like this:
            rowList.append(dataList[rowCount * i + j])
        mat.append(rowList)

    return mat
def main():
    alpha = ['a','b','c','d','e','f','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
    mat = createMatrix(1,5,alpha)
    print (mat)
    print(len(mat))
main()

[['a', 'b', 'c', 'd', 'e']]
1


In [31]:
print(len(mat))

NameError: name 'mat' is not defined